id = "smarty-zed-support"
name = "Smarty templating support"
version = "0.0.1"
schema_version = 1
authors = ["Michael van Gorkum <michaelvg94@gmail.com>"]
description = "Extension for Smarty templating support in Zed"
repository = "https://github.com/Albatrauz/smarty-zed-support"
themes = []
icon_themes = []
languages = ["languages/smarty"]
capabilities = []

[grammars.smarty]
repository = "https://github.com/hex-cat-man/tree-sitter-smarty"
rev = "6ced040bd8029c817c79e4430bfa83e72aeb1064"
